name: pactus_grpc
description: Generated gRPC Dart code for the Pactus project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  grpc: ^3.0.0

dev_dependencies:
  protobuf: ^2.0.0
  build_runner: ^2.0.0
