name: Packager
permissions:
  contents: read
  id-token: write

on:
  workflow_run:
    workflows: ["Releaser"]
    types: ["completed"]

jobs:
  packager:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Create Packages
        run: bash ./.github/packager/packager.sh

      - name: Upload Pactus grpc npm package
        uses: actions/upload-artifact@v4
        with:
          name: package-js-grpc
          path: packages/js/pactus-grpc

      - name: Upload Pactus jsonrpc npm package
        uses: actions/upload-artifact@v4
        with:
          name: package-js-jsonrpc
          path: packages/js/pactus-jsonrpc

      - name: Upload Pactus grpc PyPI package
        uses: actions/upload-artifact@v4
        with:
          name: package-python-grpc
          path: packages/python/pactus-grpc

#      TODO package python jsonrpc
#      - name: Upload Pactus jsonrpc PyPI package
#        uses: actions/upload-artifact@v4
#        with:
#          name: package-python-jsonrpc
#          path: packages/python/pactus-jsonrpc


  publish-npm-grpc:
    name: Publish pactus-grpc package 📦 to npm
    needs: packager
    runs-on: ubuntu-latest

    environment:
      name: npm
      url: https://www.npmjs.com/package/pactus-grpc

    steps:
      - name: Download JavaScript Package
        uses: actions/download-artifact@v4
        with:
          name: package-js-grpc

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}

  publish-npm-jsonrpc:
    name: Publish pactus-jsonrpc package 📦 to npm
    needs: packager
    runs-on: ubuntu-latest

    environment:
      name: npm
      url: https://www.npmjs.com/package/pactus-jsonrpc

    steps:
      - name: Download JavaScript Package
        uses: actions/download-artifact@v4
        with:
          name: package-js-jsonrpc

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}

  publish-pypi-grpc:
    name: Publish pactus-grpc package 📦 to PyPI
    needs: packager
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/pactus-grpc

    steps:
      - name: Download Python Package
        uses: actions/download-artifact@v4
        with:
          name: package-python-grpc

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build tools and build Python wheel
        run: |
          python3 -m pip install build --user
          python3 -m build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

#  TODO publish pypi package for jsonrpc
#  publish-pypi-jsonrpc:
#    name: Publish pactus-jsonrpc package 📦 to PyPI
#    needs: packager
#    runs-on: ubuntu-latest
#
#    environment:
#      name: pypi
#      url: https://pypi.org/p/pactus-jsonrpc
#
#    steps:
#      - name: Download Python Package
#        uses: actions/download-artifact@v4
#        with:
#          name: package-python-jsonrpc
#
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: "3.13"
#
#      - name: Install build tools and build Python wheel
#        run: |
#          python3 -m pip install build --user
#          python3 -m build
#
#      - name: Publish distribution 📦 to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
